#!/bin/bash

echo "... Copying dependancies ..."

cp ../../../Type.js/src/Type.js .
cp ../../../Util.js/src/Util.js .
cp ../Style.js .

echo "... Creating object files for JavaScript libraries ..."

ld -r -b binary -o Type.js.o Type.js
ld -r -b binary -o Util.js.o Util.js
ld -r -b binary -o Style.js.o Style.js

echo "... Cleanup dependancy files ..."

rm -f Type.js Util.js Style.js

echo "... Compiling ..."

g++ -O3 -Werror stylejs.cpp stylec.cpp Type.js.o Util.js.o Style.js.o -o bin/stylec /projects/Software/v8/libv8.a -lpthread && strip bin/stylec && bin/stylec -v