#!/bin/bash

ld -r -b binary -o Style.js.o Style.js

g++ -O3 -Werror stylejs.cpp stylec.cpp Style.js.o -o stylec /projects/Software/v8/libv8.a -lpthread && strip stylec && ./stylec -v

./stylec -o tmp.css example.css.js