#!/bin/bash

ld -r -b binary -o JSS.js.o JSS.js

g++ -O3 -Werror --std=c++0x jss.cpp jssc.cpp JSS.js.o -o jssc /projects/Software/v8/libv8.a -lpthread && strip jssc && ./jssc -v

./jssc -o tmp.css example.css.js